name: Conda Package

on: [push]

jobs:
  test:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Show conda info
        shell: bash -el {0}
        run: |
          conda info
          conda list
      - name: Build and conda package
        shell: bash -el {0}
        run: conda build --channel conda-forge --channel pyscf recipe
